### ISSUE TITLE
icon update when state changes

### ISSUE THREAD

**Issue by oberon-manjaro** [oleerik/comptray#1]
This is super cool! :)
When I kill Compton the icon is not updated. At the same time, right clicking on the icon shows the correct state. Would it be possible to update the icon at least at certain intervals?

**Comment by lillelilje** [comment]
It is possible and rather easy to add to be honest. I'll add it later today :)

**Comment by lillelilje** [comment]
The question is if it's worth the extra performance it'll need.
How often do you think it would be reasonable to check?

**Comment by oberon-manjaro** [comment]
1second? or 2 maybe?

**Comment by lillelilje** [comment]
Alright. I'll do it after work

**Comment by oberon-manjaro** [comment]
no hurry at all!! :smile:

**Comment by shinnova** [comment]
Added to the code so the icon will now update max 1 second after compton is toggled!

**Comment by lillelilje** [comment]
Closing issue.
Reference: https://github.com/oleerik/comptray/commit/c00690e1c900887df84b872461420fbf63bae3c0

**Comment by oberon-manjaro** [comment]
Wow! Great service here! :impressed: :D

**Comment by lillelilje** [comment]
![Image of Yaktocat](https://octodex.github.com/images/yaktocat.png)

**Comment by oberon-manjaro** [comment]
:open_mouth:

**Comment by oberon-manjaro** [comment]
So. Finally testing it :) Works supergreat!
Don't know if it is relevant but just wanted to let you know about this:

```
$ comptray
/usr/local/bin/comptray:90: GtkWarning: IA__gtk_status_icon_get_icon_name: assertion 'priv->storage_type == GTK_IMAGE_ICON_NAME || priv->storage_type == GTK_IMAGE_EMPTY' failed
  if tray.get_icon_name() == check_for_update():
```

**Comment by lillelilje** [comment]
Could you test again now? Should be good.

**Comment by oleerik** [comment]
Also I made this:
# Maintainer: Ole Erik Brennhagen <elo@tuta.io>
# Contributors: ShinNova

pkgname=comptray
pkgver=20150925
pkgrel=1
pkgdesc="Compton tray icon"
arch=('any')
_git="https://github.com/oleerik/$pkgname"
license=('GPL')
depends=('python2' 'gtk3' 'pygtk' 'compton')
optdepends=('compton-conf: GUI config')
makedepends=('git')
source=("${_git}.git")
md5sums=('SKIP')

package() {
  mkdir -p "$pkgdir/usr/bin"
  git clone $source
  cd "$srcdir/$pkgname"
  install -m755 "$pkgname" "$pkgdir/usr/bin/$pkgname"
}

**Comment by oberon-manjaro** [comment]
It's perfect now! :trophy:
